"""
ComplyFlow - Synthetic Data Generator
====================================
Generates realistic, reproducible synthetic compliance operations datasets
strictly following the approved Phase 2A domain model:
1. ComplianceRequest (150 records)
2. RequestAuditLog (milestone audit events)
3. SLAPolicy (4 reference tiers)

DISCLAIMER:
All entities, names, identifiers, transactions, and scenarios generated by
this script are 100% synthetic and fictional. They do not represent real
financial-services customer data, proprietary systems, or StoneX Group data.
"""

import csv
import random
from datetime import datetime, timedelta
from pathlib import Path

# --- Configuration & Fixed Seed for Reproducibility ---
RANDOM_SEED = 42
TOTAL_RECORDS = 150
SIMULATION_END_DATE = datetime(2026, 9, 26, 17, 0, 0)
SIMULATION_WINDOW_DAYS = 90
SIMULATION_START_DATE = SIMULATION_END_DATE - timedelta(days=SIMULATION_WINDOW_DAYS)

# Target Output Directory
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "data" / "raw"

# --- Domain Constants ---
REQUEST_TYPES = [
    "KYC Review",
    "PEP Review",
    "AML Transaction Inquiry",
    "Sanctions Review",
    "Policy Exception",
]

PROCESS_AREAS = [
    "Customer Onboarding",
    "AML Operations",
    "KYC Operations",
    "Sanctions",
    "Policy & Governance",
]

# Process Area to Request Type Affinity (Realistic weighting)
PROCESS_TO_TYPE_WEIGHTS = {
    "Customer Onboarding": [("KYC Review", 0.60), ("PEP Review", 0.30), ("Sanctions Review", 0.10)],
    "AML Operations": [("AML Transaction Inquiry", 0.85), ("PEP Review", 0.15)],
    "KYC Operations": [("KYC Review", 0.70), ("PEP Review", 0.30)],
    "Sanctions": [("Sanctions Review", 0.90), ("AML Transaction Inquiry", 0.10)],
    "Policy & Governance": [("Policy Exception", 0.90), ("KYC Review", 0.10)],
}

RISK_LEVELS = ["Low", "Medium", "High", "Critical"]
RISK_WEIGHTS = [0.25, 0.35, 0.27, 0.13]  # Non-uniform: Medium & High most common

SLA_POLICIES = {
    "Critical": {
        "SLATargetHours": 24,
        "WarningThresholdHours": 6,
        "ApprovalMandatory": 1,
        "DefaultEscalationRole": "Head of Compliance",
    },
    "High": {
        "SLATargetHours": 72,
        "WarningThresholdHours": 24,
        "ApprovalMandatory": 1,
        "DefaultEscalationRole": "Compliance Team Lead",
    },
    "Medium": {
        "SLATargetHours": 120,
        "WarningThresholdHours": 24,
        "ApprovalMandatory": 0,
        "DefaultEscalationRole": "Operational Queue Manager",
    },
    "Low": {
        "SLATargetHours": 240,
        "WarningThresholdHours": 48,
        "ApprovalMandatory": 0,
        "DefaultEscalationRole": "Operations Supervisor",
    },
}

DEPARTMENTS = [
    "Corporate Onboarding",
    "Wealth Management",
    "Institutional Sales",
    "Trade Operations",
    "Treasury",
]

COMPLIANCE_TEAMS = [
    "Financial Crime Compliance",
    "Regulatory Operations",
    "Sanctions Advisory",
]

ANALYSTS = [
    ("Elena Vance", "elena.vance@complyflow-demo.internal", "Financial Crime Compliance"),
    ("Marcus Brody", "marcus.brody@complyflow-demo.internal", "Regulatory Operations"),
    ("Aisha Patel", "aisha.patel@complyflow-demo.internal", "Financial Crime Compliance"),
    ("Liam O'Connor", "liam.oconnor@complyflow-demo.internal", "Sanctions Advisory"),
    ("Sofia Rodriguez", "sofia.rodriguez@complyflow-demo.internal", "Regulatory Operations"),
    ("Chen Wei", "chen.wei@complyflow-demo.internal", "Sanctions Advisory"),
]

MANAGERS = [
    ("David Sterling", "david.sterling@complyflow-demo.internal", "Head of Compliance"),
    ("Rachel Kensington", "rachel.kensington@complyflow-demo.internal", "Compliance Team Lead"),
    ("Arthur Pendelton", "arthur.pendelton@complyflow-demo.internal", "Operational Queue Manager"),
]

REQUESTERS = [
    ("James Wilson", "james.wilson@complyflow-demo.internal", "Institutional Sales"),
    ("Claire Dupont", "claire.dupont@complyflow-demo.internal", "Corporate Onboarding"),
    ("Tariq Al-Mansoor", "tariq.mansoor@complyflow-demo.internal", "Wealth Management"),
    ("Hannah Schmidt", "hannah.schmidt@complyflow-demo.internal", "Trade Operations"),
    ("Oliver Queen", "oliver.queen@complyflow-demo.internal", "Treasury"),
    ("Grace Hopper", "grace.hopper@complyflow-demo.internal", "Corporate Onboarding"),
    ("Mateo Silva", "mateo.silva@complyflow-demo.internal", "Institutional Sales"),
]

FICTIONAL_ENTITIES = [
    "Apex Global Logistics Ltd", "Merlion Maritime Trading Ltd", "Solaris Capital Partners",
    "Horizon Commodity Trading UK", "Delta Equity Asset Desk", "Vanguard Steel & Mining Corp",
    "Beacon Renewable Assets AG", "Crestview Private Wealth Trust", "Boreal Energy Holdings",
    "Atlas Clearing Services SA", "Zephyr Commercial Freight", "Novalink Digital Payments"
]

CASE_NARRATIVES = {
    "KYC Review": "Periodic review of corporate registration, ultimate beneficial ownership (UBO) structure (>25%), and proof of operating address.",
    "PEP Review": "Screening alert match identifying a non-executive director with senior political nexus; enhanced due diligence required.",
    "AML Transaction Inquiry": "Secondary investigation into structured cross-border wire transfers exceeding internal surveillance thresholds.",
    "Sanctions Review": "Pre-trade vessel and counterparty screening for freight handling near conditional maritime jurisdictions.",
    "Policy Exception": "Trading desk seeking temporary 5-day risk limit headroom variance pending quarterly settlement window.",
}


def weighted_choice(choices_with_weights):
    items, weights = zip(*choices_with_weights)
    return random.choices(items, weights=weights, k=1)[0]


def format_dt(dt):
    return dt.strftime("%Y-%m-%d %H:%M:%S") if dt else ""


def generate_datasets():
    random.seed(RANDOM_SEED)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # -------------------------------------------------------------
    # 1. Generate SLAPolicy Dataset
    # -------------------------------------------------------------
    sla_policy_rows = []
    for risk, policy in SLA_POLICIES.items():
        sla_policy_rows.append({
            "RiskLevel": risk,
            "SLATargetHours": policy["SLATargetHours"],
            "WarningThresholdHours": policy["WarningThresholdHours"],
            "ApprovalMandatory": policy["ApprovalMandatory"],
            "DefaultEscalationRole": policy["DefaultEscalationRole"],
        })

    sla_policy_path = OUTPUT_DIR / "sla_policies.csv"
    with open(sla_policy_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "RiskLevel", "SLATargetHours", "WarningThresholdHours",
            "ApprovalMandatory", "DefaultEscalationRole"
        ])
        writer.writeheader()
        writer.writerows(sla_policy_rows)

    # -------------------------------------------------------------
    # 2. Plan 150 ComplianceRequest Records
    # -------------------------------------------------------------
    # Target Status Breakdown:
    # Closed: 100 cases
    # Open: 50 cases
    #   - Draft: 4
    #   - Submitted: 6 (unassigned, fresh)
    #   - Under Review: 18 (in active investigation)
    #   - Pending Approval: 8 (awaiting manager sign-off)
    #   - Escalated: 6 (under escalation)
    #   - Approved (awaiting archive): 5
    #   - Rejected (awaiting archive): 3
    # Total = 100 + 4 + 6 + 18 + 8 + 6 + 5 + 3 = 150
    status_quotas = {
        "Closed": 100,
        "Draft": 4,
        "Submitted": 6,
        "Under Review": 18,
        "Pending Approval": 8,
        "Escalated": 6,
        "Approved": 5,
        "Rejected": 3,
    }

    status_pool = []
    for st, count in status_quotas.items():
        status_pool.extend([st] * count)
    random.shuffle(status_pool)

    requests = []
    audit_logs = []
    audit_id_counter = 1

    # Distribution of Process Areas (Non-uniform)
    process_area_weights = [
        ("Customer Onboarding", 0.28),
        ("AML Operations", 0.24),
        ("KYC Operations", 0.22),
        ("Sanctions", 0.14),
        ("Policy & Governance", 0.12),
    ]

    for i in range(1, TOTAL_RECORDS + 1):
        request_id = f"CR-2026-{i:04d}"
        target_status = status_pool[i - 1]

        # 1. Categorization
        process_area = weighted_choice(process_area_weights)
        request_type = weighted_choice(PROCESS_TO_TYPE_WEIGHTS[process_area])
        risk_level = random.choices(RISK_LEVELS, weights=RISK_WEIGHTS, k=1)[0]
        policy = SLA_POLICIES[risk_level]
        sla_target_hours = policy["SLATargetHours"]
        approval_required = policy["ApprovalMandatory"]

        # Priority: normally matches risk, 15% bumped for operational urgency
        if random.random() < 0.15 and risk_level != "Critical":
            priority_idx = min(len(RISK_LEVELS) - 1, RISK_LEVELS.index(risk_level) + 1)
            priority = RISK_LEVELS[priority_idx]
        else:
            priority = risk_level

        # Submitter
        requester_name, requester_email, requester_dept = random.choice(REQUESTERS)
        fictional_entity = random.choice(FICTIONAL_ENTITIES)
        title = f"{request_type} - {fictional_entity}"
        description = f"{CASE_NARRATIVES[request_type]} Counterparty: {fictional_entity}. Request initiated by {requester_dept}."

        # 2. Timing Allocation
        # Distribute submission dates across the 90-day simulation window
        if target_status == "Closed":
            # Closed cases submitted earlier in the window (days 0 to 82)
            days_ago = random.uniform(8.0, float(SIMULATION_WINDOW_DAYS))
        elif target_status in ["Draft", "Submitted"]:
            # Very recent cases (last 0.2 to 2 days)
            days_ago = random.uniform(0.1, 2.5)
        else:
            # Active in-flight cases (last 0.5 to 12 days)
            days_ago = random.uniform(0.5, 14.0)

        submission_dt = SIMULATION_END_DATE - timedelta(days=days_ago)
        # CreatedDate is slightly before or equal to submission
        created_dt = submission_dt - timedelta(minutes=random.randint(5, 120))
        target_due_dt = submission_dt + timedelta(hours=sla_target_hours)

        # 3. Lifecycle state and attribute resolution
        completion_dt = None
        assigned_analyst = ""
        assigned_analyst_email = ""
        compliance_team = ""
        approved_by = ""
        approval_date = None
        escalation_flag = 0
        escalated_to = ""
        escalation_reason = ""
        closure_notes = ""
        sla_breach_flag = 0

        # Assigned Analyst (unless Draft or Submitted)
        if target_status not in ["Draft", "Submitted"]:
            analyst_name, analyst_email, team = random.choice(ANALYSTS)
            assigned_analyst = analyst_name
            assigned_analyst_email = analyst_email
            compliance_team = team
        elif target_status == "Submitted":
            # Compliance team assigned, but individual analyst not yet picked up
            compliance_team = random.choice(COMPLIANCE_TEAMS)

        # Handle Closed Cases
        if target_status == "Closed":
            # Decide if case was completed within SLA or breached (18% realistic breach rate)
            will_breach = random.random() < 0.18
            if will_breach:
                # Breached SLA: completed past target due date
                extra_hours = random.uniform(2.0, min(72.0, sla_target_hours * 0.8))
                completion_dt = target_due_dt + timedelta(hours=extra_hours)
                sla_breach_flag = 1
            else:
                # Within SLA: completed between 15% and 85% of SLA target
                duration_hours = random.uniform(sla_target_hours * 0.15, sla_target_hours * 0.85)
                completion_dt = submission_dt + timedelta(hours=duration_hours)
                sla_breach_flag = 0

            # Guard: Completion cannot be after SIMULATION_END_DATE
            if completion_dt > SIMULATION_END_DATE:
                completion_dt = SIMULATION_END_DATE - timedelta(hours=random.uniform(1.0, 4.0))
                sla_breach_flag = 1 if completion_dt > target_due_dt else 0

            # Was it approved or rejected? (88% approved, 12% rejected)
            is_rejection = random.random() < 0.12
            if approval_required:
                mgr = random.choice(MANAGERS)[0]
                approved_by = mgr
                approval_date = completion_dt - timedelta(hours=random.uniform(0.5, 3.0))

            if is_rejection:
                closure_notes = f"Review concluded with rejection. Counterparty documentation failed verification under {process_area} risk policy."
            else:
                closure_notes = f"Review successfully concluded and verified under {process_area} compliance requirements."

            # Did a closed case experience escalation during its lifecycle? (10% of closed)
            if random.random() < 0.10:
                escalation_flag = 1
                escalated_to = policy["DefaultEscalationRole"]
                escalation_reason = "Complex jurisdictional nexus requiring specialist review."

        # Handle Open Active Cases
        else:
            # Check SLA breach status relative to SIMULATION_END_DATE
            if SIMULATION_END_DATE > target_due_dt:
                sla_breach_flag = 1  # Currently overdue!
            else:
                sla_breach_flag = 0

            if target_status == "Escalated":
                escalation_flag = 1
                escalated_to = policy["DefaultEscalationRole"]
                if sla_breach_flag == 1:
                    escalation_reason = "Automated escalation: Target SLA turnaround breached."
                else:
                    escalation_reason = "Urgent counterparty risk query flagged during preliminary review."

            elif target_status == "Pending Approval":
                if approval_required:
                    # In pending approval, waiting on manager
                    pass
                else:
                    # Rare scenario: Medium risk voluntarily escalated for manager endorsement
                    approval_required = 1

            elif target_status in ["Approved", "Rejected"]:
                # Open, finalized review awaiting administrative closure/archiving
                if approval_required:
                    approved_by = random.choice(MANAGERS)[0]
                    approval_date = SIMULATION_END_DATE - timedelta(hours=random.uniform(1.0, 12.0))
                closure_notes = "Review completed; awaiting final administrative filing."

        modified_dt = completion_dt if completion_dt else min(SIMULATION_END_DATE, submission_dt + timedelta(hours=random.uniform(1.0, 8.0)))

        # Compile Request Record
        req_record = {
            "RequestID": request_id,
            "Title": title,
            "RequestType": request_type,
            "ProcessArea": process_area,
            "RiskLevel": risk_level,
            "Priority": priority,
            "Status": target_status,
            "Description": description,
            "RequesterName": requester_name,
            "RequesterEmail": requester_email,
            "RequesterDepartment": requester_dept,
            "AssignedAnalyst": assigned_analyst,
            "AssignedAnalystEmail": assigned_analyst_email,
            "ComplianceTeam": compliance_team,
            "SubmissionDateTime": format_dt(submission_dt),
            "TargetDueDateTime": format_dt(target_due_dt),
            "CompletionDateTime": format_dt(completion_dt),
            "SLATargetHours": sla_target_hours,
            "SLABreachFlag": sla_breach_flag,
            "ApprovalRequired": approval_required,
            "ApprovedBy": approved_by,
            "ApprovalDate": format_dt(approval_date),
            "EscalationFlag": escalation_flag,
            "EscalatedTo": escalated_to,
            "EscalationReason": escalation_reason,
            "ClosureNotes": closure_notes,
            "CreatedDate": format_dt(created_dt),
            "ModifiedDate": format_dt(modified_dt),
        }
        requests.append(req_record)

        # -------------------------------------------------------------
        # 3. Generate Chronological Milestone Audit Logs
        # -------------------------------------------------------------
        # Every request starts with Created
        audit_logs.append({
            "AuditID": audit_id_counter,
            "RequestID": request_id,
            "Timestamp": format_dt(created_dt),
            "ActionType": "Created",
            "PerformedBy": requester_name,
            "OldStatus": "",
            "NewStatus": "Draft",
            "Comments": "Request drafted by requester.",
        })
        audit_id_counter += 1

        if target_status == "Draft":
            continue

        # Milestone: Submitted
        audit_logs.append({
            "AuditID": audit_id_counter,
            "RequestID": request_id,
            "Timestamp": format_dt(submission_dt),
            "ActionType": "Submitted",
            "PerformedBy": requester_name,
            "OldStatus": "Draft",
            "NewStatus": "Submitted",
            "Comments": f"Request formally submitted to {compliance_team} queue. SLA clock started.",
        })
        audit_id_counter += 1

        if target_status == "Submitted":
            continue

        # Milestone: Assigned -> Under Review
        assign_dt = submission_dt + timedelta(minutes=random.randint(15, 180))
        if completion_dt and assign_dt > completion_dt:
            assign_dt = submission_dt + (completion_dt - submission_dt) * 0.2
        if assign_dt > SIMULATION_END_DATE:
            assign_dt = submission_dt + (SIMULATION_END_DATE - submission_dt) * 0.3

        audit_logs.append({
            "AuditID": audit_id_counter,
            "RequestID": request_id,
            "Timestamp": format_dt(assign_dt),
            "ActionType": "Assigned",
            "PerformedBy": assigned_analyst,
            "OldStatus": "Submitted",
            "NewStatus": "Under Review",
            "Comments": f"Case assigned to analyst {assigned_analyst}. Investigation commenced.",
        })
        audit_id_counter += 1

        if target_status == "Under Review":
            continue

        esc_dt = None
        # Milestone: Escalated (if applicable during active lifecycle)
        if escalation_flag and (target_status == "Escalated" or random.random() < 0.5):
            esc_dt = assign_dt + timedelta(hours=random.uniform(1.0, 12.0))
            if completion_dt and esc_dt >= completion_dt:
                esc_dt = assign_dt + (completion_dt - assign_dt) * 0.5
            if esc_dt > SIMULATION_END_DATE:
                esc_dt = assign_dt + (SIMULATION_END_DATE - assign_dt) * 0.5

            audit_logs.append({
                "AuditID": audit_id_counter,
                "RequestID": request_id,
                "Timestamp": format_dt(esc_dt),
                "ActionType": "Escalated",
                "PerformedBy": "System Automation" if "turnaround" in escalation_reason.lower() else assigned_analyst,
                "OldStatus": "Under Review",
                "NewStatus": "Escalated",
                "Comments": f"Escalated to {escalated_to}. Reason: {escalation_reason}",
            })
            audit_id_counter += 1

            if target_status == "Escalated":
                continue

        # Milestone: Approval Requested (if approval required)
        base_prev_dt = esc_dt if (escalation_flag and esc_dt) else assign_dt
        if approval_required:
            if completion_dt:
                req_appr_dt = base_prev_dt + (completion_dt - base_prev_dt) * 0.4
                appr_dt = base_prev_dt + (completion_dt - base_prev_dt) * 0.8
            else:
                req_appr_dt = base_prev_dt + timedelta(hours=random.uniform(2.0, 8.0))
                if req_appr_dt > SIMULATION_END_DATE:
                    req_appr_dt = base_prev_dt + (SIMULATION_END_DATE - base_prev_dt) * 0.5
                appr_dt = req_appr_dt + timedelta(hours=random.uniform(1.0, 4.0))
                if appr_dt > SIMULATION_END_DATE:
                    appr_dt = req_appr_dt + (SIMULATION_END_DATE - req_appr_dt) * 0.5

            audit_logs.append({
                "AuditID": audit_id_counter,
                "RequestID": request_id,
                "Timestamp": format_dt(req_appr_dt),
                "ActionType": "Approval Requested",
                "PerformedBy": assigned_analyst,
                "OldStatus": "Under Review",
                "NewStatus": "Pending Approval",
                "Comments": "Analyst findings completed; routed to compliance management for sign-off.",
            })
            audit_id_counter += 1

            if target_status == "Pending Approval":
                continue

            action = "Approved" if approved_by else "Rejected"
            if approved_by:
                req_record["ApprovalDate"] = format_dt(appr_dt)

            audit_logs.append({
                "AuditID": audit_id_counter,
                "RequestID": request_id,
                "Timestamp": format_dt(appr_dt),
                "ActionType": action,
                "PerformedBy": approved_by if approved_by else assigned_analyst,
                "OldStatus": "Pending Approval",
                "NewStatus": action,
                "Comments": f"Management sign-off granted by {approved_by}." if action == "Approved" else "Denied by compliance management.",
            })
            audit_id_counter += 1

        else:
            # Low/Medium risk: sign-off directly by analyst
            action = "Approved" if target_status in ["Approved", "Closed"] and "rejection" not in closure_notes.lower() else "Rejected"
            if completion_dt:
                direct_dt = base_prev_dt + (completion_dt - base_prev_dt) * 0.7
            else:
                direct_dt = base_prev_dt + timedelta(hours=random.uniform(2.0, 12.0))
                if direct_dt > SIMULATION_END_DATE:
                    direct_dt = base_prev_dt + (SIMULATION_END_DATE - base_prev_dt) * 0.7

            audit_logs.append({
                "AuditID": audit_id_counter,
                "RequestID": request_id,
                "Timestamp": format_dt(direct_dt),
                "ActionType": action,
                "PerformedBy": assigned_analyst,
                "OldStatus": "Under Review",
                "NewStatus": action,
                "Comments": f"Analyst concluded review with outcome: {action}.",
            })
            audit_id_counter += 1

        if target_status in ["Approved", "Rejected"]:
            continue

        # Milestone: Closed
        audit_logs.append({
            "AuditID": audit_id_counter,
            "RequestID": request_id,
            "Timestamp": format_dt(completion_dt),
            "ActionType": "Closed",
            "PerformedBy": assigned_analyst,
            "OldStatus": "Approved" if "rejection" not in closure_notes.lower() else "Rejected",
            "NewStatus": "Closed",
            "Comments": f"Case finalized and archived. Notes: {closure_notes[:60]}...",
        })
        audit_id_counter += 1

    # -------------------------------------------------------------
    # 4. Write CSV Outputs
    # -------------------------------------------------------------
    req_path = OUTPUT_DIR / "compliance_requests.csv"
    with open(req_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "RequestID", "Title", "RequestType", "ProcessArea", "RiskLevel",
            "Priority", "Status", "Description", "RequesterName", "RequesterEmail",
            "RequesterDepartment", "AssignedAnalyst", "AssignedAnalystEmail",
            "ComplianceTeam", "SubmissionDateTime", "TargetDueDateTime",
            "CompletionDateTime", "SLATargetHours", "SLABreachFlag",
            "ApprovalRequired", "ApprovedBy", "ApprovalDate", "EscalationFlag",
            "EscalatedTo", "EscalationReason", "ClosureNotes", "CreatedDate",
            "ModifiedDate"
        ])
        writer.writeheader()
        writer.writerows(requests)

    audit_path = OUTPUT_DIR / "request_audit_log.csv"
    with open(audit_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "AuditID", "RequestID", "Timestamp", "ActionType", "PerformedBy",
            "OldStatus", "NewStatus", "Comments"
        ])
        writer.writeheader()
        writer.writerows(audit_logs)

    print(f"[SUCCESS] Synthetic data generated successfully in '{OUTPUT_DIR}':")
    print(f"  - compliance_requests.csv: {len(requests)} rows")
    print(f"  - request_audit_log.csv:   {len(audit_logs)} rows")
    print(f"  - sla_policies.csv:        {len(sla_policy_rows)} rows")


if __name__ == "__main__":
    generate_datasets()
